language: dart
sudo: required
dist: trusty
dart:
  - stable
  - beta
  - dev
before_script:
  - cd repo_support
  - dart pub get
  - dart pub run tekartik_travis_ci_flutter:install
  - source $(dart pub run tekartik_travis_ci_flutter:env)
script:
  - dart tool/travis.dart
matrix:
  allow_failures:
    - dart: dev