name: tekartik_bluetooth_flutter_blue
description: Bluetooth flutter blue specific
version: 0.4.0
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.5.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: '>=0.6.0+1'
  uuid:
  synchronized:
  tekartik_bluetooth:
    git:
      url: git://github.com/tekartik/bluetooth.dart
      path: bluetooth
      ref: dart2
    version: '>=0.2.1'
  tekartik_bluetooth_flutter:
    git:
      url: git://github.com/tekartik/bluetooth.dart
      path: bluetooth_flutter
      ref: dart2
    version: '>=0.2.1'
dependency_overrides:
  tekartik_bluetooth:
    path: ../bluetooth
  tekartik_bluetooth_flutter:
    path: ../bluetooth_flutter
  # flutter_blue:
  #  git:
  #    url: git://github.com/pauldemarco/flutter_blue

dev_dependencies:
  build_runner:
  test:
  flutter_test:
    sdk: flutter
  process_run:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.


  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
