name: tekartik_bluetooth
description: Bluetooth abstraction
version: 0.5.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta:
  collection:
  uuid:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.7+1'
  rxdart:

dev_dependencies:
  test:
  process_run: