name: tekartik_bluetooth
description: Bluetooth abstraction
version: 0.5.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Temp pre-nnbd
  # uuid: '<=3.0.0-0'
  uuid:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: null_safety
    version: '>=0.10.7+1'
  rxdart:

dev_dependencies:
  test:
  process_run: