name: tekartik_bluetooth
description: Bluetooth abstraction
version: 0.6.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta:
  collection:
  uuid:
  cv:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7+1'
  rxdart:

dev_dependencies:
  test:
  process_run:
