name: tekartik_bluetooth
description: Bluetooth abstraction
version: 0.6.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  meta: ">=1.15.0"
  collection: ">=1.18.0"
  uuid: '>=4.1.0'
  cv: ">=1.1.0+4"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7+1'
  rxdart:

dev_dependencies:
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
