name: tekartik_bluetooth
description: Bluetooth abstraction
version: 0.6.1
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  meta:
  collection:
  uuid: '>=4.1.0'
  cv: '>=0.2.13'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7+1'
  rxdart:

dev_dependencies:
  test:
  process_run:
