name: tekartik_bluetooth_web
description: Bluetooth for the web
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0


dependencies:
  flutter_web_bluetooth:
    git:
      url: https://github.com/tekartikdev/flutter_web_bluetooth.git
  tekartik_bluetooth:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth
      ref: dart3a
    version: '>=0.2.1'

dependency_overrides:
  tekartik_bluetooth:
    path: ../bluetooth

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  tekartik_test_menu_browser:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_browser
      ref: dart3a
    version: '>=0.4.7'
