name: tekartik_bluetooth_server_flutter
description: Flutter server implementation
version: 0.2.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tekartik_bluetooth_flutter_blue:
    git:
      url: git://github.com/tekartik/bluetooth.dart
      path: bluetooth_flutter_blue
      ref: null_safety
    version: '>=0.2.1'
  tekartik_bluetooth_server:
    git:
      url: git://github.com/tekartik/bluetooth.dart
      path: bluetooth_server
      ref: null_safety
    version: '>=0.2.1'

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  tekartik_lints_flutter:
    git:
      url: git://github.com/tekartik/common_flutter.dart
      ref: null_safety
      path: packages/lints_flutter
    version: '>=0.1.0'

dependency_overrides:
  tekartik_bluetooth:
    path: ../bluetooth
  tekartik_bluetooth_flutter_blue:
    path: ../bluetooth_flutter_blue
  tekartik_bluetooth_flutter:
    path: ../bluetooth_flutter
  tekartik_bluetooth_server:
    path: ../bluetooth_server
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
