name: bluetooth_repo_support
description: Bluetoooth support tools
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: null_safety
    version: '>=0.1.0'
  process_run: '>=0.11.0+2'
  dev_test: '>=0.13.4-dev.2'
  test:
  tekartik_lints:
    git:
      url: git://github.com/tekartik/common.dart
      ref: null_safety
      path: packages/lints
    version: '>=0.1.0'