name: tekartik_bluetooth_bluez
description: Bluetooth on linux
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.15.0-0 <3.0.0'

dependencies:
  tekartik_bluetooth:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth
      ref: dart2_3
    version: '>=0.2.1'
  bluez:
  dbus:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  tekartik_bluetooth:
    path: ../bluetooth