name: tekartik_bluetooth_bluez
description: Bluetooth on linux
version: 0.5.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  tekartik_bluetooth:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth
      ref: dart3a
    version: '>=0.2.1'
  bluez: '>=0.8.1'
  dbus:

dev_dependencies:
  test: ">=1.24.0"

dependency_overrides:
  tekartik_bluetooth:
    path: ../bluetooth
