name: tekartik_bluetooth_test_app
description: Simple bluetooth test app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  tekartik_app_platform:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_platform
    version: '>=0.1.0'
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: '>=0.1.2'
  rxdart: '>=0.26.0'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart2_3
      path: platform_io
  tekartik_bluetooth_web:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth_flutter
      ref: dart2_3
  flutter_blue_plus:
dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run: '>=0.10.3'
  test:
  tekartik_bluetooth_flutter_blue:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth_flutter_blue
      ref: dart2_3
    version: '>=0.2.1'
  tekartik_bluetooth_bluez:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth_bluez
      ref: dart2_3
    version: '>=0.2.1'
  tekartik_test_menu_flutter:
    git:
      url: https://github.com/tekartik/test_menu_flutter
      ref: dart2_3
      path: test_menu_flutter
    version: '>=0.2.5'
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      ref: dart2_3
      path: packages/lints_flutter
    version: '>=0.1.0'
  tekartik_build_menu_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart2_3
      path: packages/build_menu_flutter
    version: '>=0.1.0'
dependency_overrides:
  # temp dev_dependencies:
  # tekartik_build_flutter:
  #  path: ../../../tekartik/build_flutter.dart/packages/build_flutter

  tekartik_bluetooth:
    path: ../bluetooth
  tekartik_bluetooth_bluez:
    path: ../bluetooth_bluez
  tekartik_bluetooth_flutter_blue:
    path: ../bluetooth_flutter_blue
  tekartik_bluetooth_flutter:
    path: ../bluetooth_flutter
  tekartik_bluetooth_web:
    path: ../bluetooth_web

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages